caddy/README.md
caddy/handler.go
caddy/setup.go
caddy/setup_test.go
login/config.go
login/config_test.go
login/handler.go
login/handler_test.go
login/login_form.go
main_test.go
oauth2/manager.go

Changed the prefix handling to the parameter login-path (login_path in caddy), as mentioned in #3.
And fixed the path handling in the form template.

Fix prefix handling

---

README.md
caddy/setup_test.go
logging/logger.go
logging/logger_test.go
login/config.go
login/config_test.go
main.go

Just for the non-caddy standalone. Caddy shuts down gracefully by itself.

Implemented graceful shutdown via go 1.8 Server.Shutdown(ctx)

---

htpasswd/backend.go
htpasswd/backend_test.go

Caddy config separates his config params already with , files need an other seperator.

change files/file separator from , to ;

---

README.md

The table markup for Httpupstream section was broken. This fixes it.

fix broken table formatting for Httpupstream

---

oauth2/google.go
oauth2/google_test.go
oauth2/oauth.go
oauth2/oauth_test.go
oauth2/provider_test.go

- Adds provider for Google
- Gets user info from the Google Plus API
- Google required redirect_uri and grant_type in the exchange token step, and i assumed this wasn't harmful elsewhere. I can include this via config if you'd prefer
email scope is required for email to be returned
I am unfamiliar with testing in golang, but have attempted a test based upon your code - please let me know if anything additional is required

adds google provider

---

caddy/README.md

"login / " leads to deprecation warning and fails to start.

Updates Caddy Readme to avoid deprecation warning

---

caddy/handler.go
caddy/handler_test.go
caddy/setup_test.go
logging/logger_test.go
logging/logstash_formatter.go
login/handler.go
login/handler_test.go

I tested it on Windows 7 x64 and it works.
I've not added tests yet.
@smancke please review it. I'm unsure if it is the best way to add this feature.

Caddy - Use {user} placeholder for logs #32

---

login/config.go

JwtSecret is currently set to "random key" by ConfigureFlagSet().
Caddy will only change this if JWT_SECRET environmental variable is set meaning that it was defaulting to "random key" which is a security risk.
I've changed the default that ConfigureFlagSet() sets to be the randomly create string so that there is no danger of hard coding a jwt secret.
I have also removed some unnecessary if statements related to setting the jwt secret.

Fix issue with jwt secret defaulting to "random key" in caddy if not specified by JWT_SECRET

---

README.md

Note user that People API is required to use with Google OAuth 2. (#58)

Update README.md to note about People API for Google

---

login/login_form.go

Avoids badly proportioned non-square profile pictures. We could explicitly declare `width: auto;` as well?

login-picture auto width

---

login/handler.go
login/handler_test.go

This PR is a try to adjust behavior to resolve #71.
It changes behavior in 3 cases:
1) empty username now returns a 403 instead of a page with `Bad Request: Method or content-type not supported`
2) Refreshing an expired token returns a 403 instead of a 400
3) Refreshing an invalid token returns a 403 instead of a 400
@smancke please review it and confirm if these behavior are acceptable in these cases.

Adjust behavior on empty username and token refresh

---

caddy/setup_test.go

This test fails on Windows 7 x64 without this small adjustment.
This commit is similar to https://github.com/tarent/loginsrv/commit/8c99657f77f73d2d5b784e673eb4cd6694e3664f.

Minor correction for cross-platform filepath

---

htpasswd/auth.go

As asked for with the comment on the issue I posted.
golang.org/x/crypto/bcrypt, generate $2a$ bcrypt prefix, so it would be logical to authenticate against this prefix as well...

Allow Bcrypt $2a$ prefix

---

login/login_form.go

Add the viewport meta tag given in the Bootstrap documentation: https://getbootstrap.com/docs/3.3/getting-started/#template
Without it, the interface looks tiny on mobile:

Add viewport meta tag to get proper scaling on mobile

---

caddy/handler.go

Fixes #94.
Tested on Windows 7 x64 with PHP 7.3.0 and it sets value for $_SERVER['REMOTE_USER']. This value is empty when user isn't logged in.
Implemented like Caddy's basicauth:
https://github.com/mholt/caddy/blob/master/caddyhttp/basicauth/basicauth.go#L80
I tried adding tests, but I've not been able to for now.

let upstream middleware (e.g. fastcgi and cgi) know about authenticated user

---

README.md

The URL osiam.org is not under our control anymore. Replaced it with https://github.com/osiam/osiam.

Fix link to OSIAM

---

logging/logstash_formatter_test.go

go 1.14 will quote the url in a url.Error. Thus, the check in the logstash formatter test should be a bit more lenient.
Also see:
https://github.com/golang/go/commit/64cfe9fe22113cd6bc05a2c5d0cbe872b1b57860

Fix up broken tip build

---

.travis.yml

Don't only build against tip, but also 1.12 and 1.13. tip builds are considered failable, as tip might be in an unstable state.

Fix up travis builds

---

README.md
caddy/README.md
caddy/setup.go
caddy/setup_test.go
login/config.go
login/config_test.go

This PR implements the possibility to provide the JWT secret not only via a flag or environment variable, but also via a file.
This is especially useful for providing private keys for Elliptic Curve signing (e.g. ES512).
Exemplary use-cases are Docker Swarm Secrets (or file mounts in general), or Kubernetes secrets. See e.g. [this documentation for the mysql docker image](https://hub.docker.com/_/mysql) for an idea.

Implement option to provide jwt secret via file

---

login/config.go
oauth2/manager.go
oauth2/manager_test.go
oauth2/oauth.go

loginsrv currently uses `math/rand` with the service start time as a seed to generate oauth2 states and other secrets. This is of course an security issue and hence `math/rand` gets replaced with `crypto/rand` which [utilizes better sources of randomness](https://golang.org/pkg/crypto/rand/#pkg-variables).
Further this PR increases both the length of the default jwt secret to 2*64 byte and the length of the oauth2 state secret to 2*32 byte to avoid possible brute force attacks. (fixes #149)

Use crypto/rand

---

.travis.yml

Travis favors master now, and [gimme](https://github.com/travis-ci/gimme) even fails in some cases with "tip".

Rename tip to master in travis build file

---

.dockerignore
Dockerfile
docker_push.sh

As stated in #154, the binary is currently build against glibc, and deployed in a musl image. This PR fixes this, by moving the build into the Dockerfile.
I tried to take care to not alter the resulting image too much.

Move binary build into dockerfile

---

oauth2/github.go
oauth2/github_test.go

Fixes #165 by using the Authorization header instead of the `access_token` query param.
To test:
1. Create a new GitHub OAuth App at https://github.com/settings/developers
2. Run a server with this new version first, and login with GitHub. Verify that you did not get a deprecation notice email
3. Run the current master server, and login with GitHub. You'll see you did get a deprecation notice for the current server

Fix #165 by using Authorization header instead

---

README.md
htpasswd/backend.go
htpasswd/backend_test.go

This is a fix for #39.
It removes an undocumented parameter and enhances the doc in the main page on a related feature.

Remove undocumented "files" parameter for htpasswd and enhance doc

---

login/handler.go

Hello, the requests are failing when their `Content-Type`  header includes their charset. This is because the validation of credentials required a literal equality for the content type. I just did correct the check.
Thank you for the package.

fix login failure when JSON content type includes charset
