README.md, caddy/setup.go, caddy/setup_test.go, login/config.go, login/config_test.go, login/handler.go, login/handler_test.go, login/login_form.go, login/login_form_test.go, oauth2/github.go
Implemented parameters `template` and `logout-url`.
=> Configurable template

htpasswd/auth.go
It doesn't use a `sync.RwMutex` as I was unsure if it was required with my current implementation.
I also didn't add a test yet.
It solves the issue I mentioned in #20. It may need a bit more work though.
Please review this pull request.
=> Caddy usage - htpasswd file isn't reloaded (on insert, on update or on delete)

dev_run.sh
=> Suppress `DEPRECATED` warning

README.md, caddy/setup.go, httpupstream/auth.go, httpupstream/auth_test.go, httpupstream/backend.go, httpupstream/backend_test.go, main.go
Based slightly on a caddy module I just wrote to proxy authentication back to our internal gitlab installation.
=> Add httpupstream backend

login/login_form.go, oauth2/google.go, oauth2/google_test.go
Fix issue with picture being next to button in the logged in page.
Fix issue where parameters were being added to a url of the picture that had parameters already
=> Fix issues with picture display

README.md, oauth2/bitbucket.go, oauth2/bitbucket_test.go, oauth2/provider_test.go
This PR adds Bitbucket oauth2 as a provider
=> #51 | Added Bitbucket Oauth2 support

README.md, caddy/README.md, caddy/demo/Caddyfile, caddy/demo/redirect_hosts.txt, caddy/demo/webroot/index.html, caddy/setup.go, caddy/setup_test.go, login/config.go, login/config_test.go, login/handler.go, login/handler_test.go, login/redirect.go, login/redirect_test.go
Continue of the work  from #62.
@lhopki01
=> Dynamic redirects

README.md, oauth2/facebook.go, oauth2/facebook_test.go, oauth2/provider_test.go
This pull request adds a Facebook Oauth Service provider asked in #60
=> Facebook OAuth provider

README.md
Some small minor corrections and simplifications on the main page.
=> Minor corrections on the main page

logging/logger_test.go
A test for the related lines was currently missing.
=> Add a missing test in logger.go

README.md
Current ones only show cURL calls. I though one with an AJAX call would be helpful.
=> Add a new example under "API Examples"

README.md
Google API changed. Doc should be made more clear about it.
=> Refer to the right API

caddy/handler_test.go, caddy/setup_test.go, login/config.go, login/config_test.go, login/handler.go, login/handler_test.go
In order to set the secure flag of the token cookies a new config has been introduced. (--cookie-secure, LOGINSRV_COOKIE_SECURE). It's default value is true.
Resolves #90
=> [FEATURE] add config for cookie secure flag

README.md, login/user_claims.go, login/user_claims_test.go, model/user_info.go, model/user_info_test.go, oauth2/gitlab.go, oauth2/gitlab_test.go, oauth2/provider_test.go
=> [Feature] Adding Gitlab Provider

README.md, caddy/README.md, caddy/setup.go, caddy/setup_test.go, login/config.go
This closes #101.
@magikstm Here is another approach for #101 
I have created the test documentation and the test case first. Could you please review it and test it with your real world configs?
=> fixed corner cases in handling of JWT_SECRET paramter for caddy

README.md, caddy/README.md
This should be merged only after this PR is merged in http.jwt and available in new version: BTBurke/caddy-jwt#39
=> Doc additions to mention issues in #103

README.md
Fixes #102.
Add doc details for -cookie-name and minor doc edits.
This should be merged only after this PR is merged in http.jwt and available in new version: https://github.com/BTBurke/caddy-jwt/pull/39
=> Update README.md for issue #102

README.md, caddy/README.md
Fixes #115.
Also fixes a few other minor doc issues.
=> Fix issue 115 and a few other minor doc issues

.travis.yml
=> Only deploy the go 1.13 build

README.md
=> Update README.md - Issue #162

login/login_form.go
=> Remove rightmost "/" from login_path

README.md
=> (readme): enabled syntax highlighting
